# Config file for automatic testing at travis-ci.org

language: python

python:
    - "2.7"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/wheelhouse
    - node_modules
    - website/static/vendor/bower_components

env:
  WHEELHOUSE: $HOME/.cache/wheelhouse
  TOKU_HUGE_PAGES_OK: 1

before_install:
    # tokumx
    - curl -L -O https://s3.amazonaws.com/tokumx-2.0.0/tokumx-2.0.0-linux-x86_64-main.tar.gz
    - curl -L -O https://s3.amazonaws.com/tokumx-2.0.0/tokumx-2.0.0-linux-x86_64-main.tar.gz.md5
    - md5sum --check tokumx-2.0.0-linux-x86_64-main.tar.gz.md5
    - mkdir /tmp/tokumx
    - tar xzf tokumx-2.0.0-linux-x86_64-main.tar.gz -C /tmp/tokumx --strip-components=1
    - mkdir /tmp/tokumx/data
    - /tmp/tokumx/bin/mongod --dbpath=/tmp/tokumx/data > /dev/null &
    # elasticsearch
    - curl -L -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.5.0.tar.gz
    - curl -L -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.5.0.tar.gz.sha1.txt
    - sha1sum --check elasticsearch-1.5.0.tar.gz.sha1.txt
    - mkdir /tmp/elasticsearch
    - tar -xvf elasticsearch-1.5.0.tar.gz -C /tmp/elasticsearch --strip-components=1
    - /tmp/elasticsearch/bin/elasticsearch > /dev/null &

install:
    - cp website/settings/local-travis.py website/settings/local.py
    # - travis_retry invoke encryption
    - travis_retry pip install --upgrade pip
    - travis_retry pip install invoke==0.9.0
    - travis_retry invoke wheelhouse --dev --addons
    - travis_retry invoke travis_addon_settings
    - travis_retry invoke requirements --dev --addons
    - travis_retry invoke assets --dev

before_script:
    - flake8 .

# Run Python tests (core and addon) and JS tests
script:
    - invoke test --all

before_cache:
  - rm -Rf $HOME/.cache/pip/http/
  - rm -f $HOME/.cache/pip/log/debug.log

notifications:
   flowdock: 0221882cdda034c0e9ac2a0e766053dd
