# Config file for automatic testing at travis-ci.org

language: python

sudo: false

python:
    - "2.7"

cache:
  directories:
    - $HOME/wheelhouse

before_install:
    - export WHEELHOUSE=$HOME/wheelhouse
    #tokumx
    - export TOKU_HUGE_PAGES_OK=1
    - curl -SL "https://s3.amazonaws.com/tokumx-2.0.0/tokumx-2.0.0-linux-x86_64-main.tar.gz" -o tokumx-2.0.0.tar.gz
    - mkdir /tmp/tokumx
    - tar xzf tokumx-2.0.0.tar.gz -C /tmp/tokumx --strip-components=1
    - mkdir /tmp/tokumx/data
    - /tmp/tokumx/bin/mongod --dbpath=/tmp/tokumx/data > /dev/null &
    #elasticsearch
    - curl -L -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.4.tar.gz
    - tar -xvf elasticsearch-1.4.4.tar.gz
    - ./elasticsearch-1.4.4/bin/elasticsearch > /dev/null  &  

install:
    - cp website/settings/local-travis.py website/settings/local.py
    # - travis_retry invoke encryption
    - travis_retry pip install invoke==0.9.0 --force-reinstall --upgrade
    - travis_retry pip install flake8 --force-reinstall --upgrade
    - travis_retry invoke wheelhouse --dev --addons
    - travis_retry invoke travis_addon_settings
    - travis_retry invoke requirements --dev --addons
    - travis_retry invoke assets --dev
before_script:
    - flake8 .

# Run Python tests (core and addon) and JS tests
script:
    - invoke test --all
    - pkill elasticsearch
    - pkill mongod

cache:
  directories:
    - website/vendor/bower_components
    - $HOME/virtualenv/python2.7/lib/python2.7/site-packages

#notifications:
#    flowdock: 0221882cdda034c0e9ac2a0e766053dd
