# Config file for automatic testing at travis-ci.org

language: python
services: mongodb

python:
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - cp website/settings/local-travis.py website/settings/local.py
    - pip install invoke
    - invoke requirements
    - invoke addon_requirements --mfr 0

# command to run tests, e.g. python setup.py test
script: invoke test_all
