
version: '2'

services:

#  fakecas:
#    image: quay.io/centerforopenscience/fakecas:latest
#    command: fakecas -host=0.0.0.0:8080 -dbaddress=172.19.0.7:27017

#  wb:
#    volumes_from:
#      - container:wb-sync

#  mfr:
#    volumes_from:
#      - container:mfr-sync

#  preprints:
#    volumes_from:
#      - container:preprints-sync
#    # Use this for ember-osf link development:
#    command: /bin/bash -c "yarn --pure-lockfile --no-progress --no-emoji && ./node_modules/bower/bin/bower install --allow-root --config.interactive=false && npm link ../ember-osf && ./node_modules/ember-cli/bin/ember serve --host 0.0.0.0 --port 4200"
#    volumes:
#      - preprints_dist_vol:/code/dist
#      - ../ember-osf:/ember-osf

#  registries:
#    volumes_from:
#      - container:registries-sync

  requirements:
    volumes_from:
      - container:osf-sync

  assets:
    volumes_from:
      - container:osf-sync

  admin_assets:
    volumes_from:
      - container:osf-sync

  sharejs:
    volumes_from:
      - container:osf-sync

#  beat:
#    volumes_from:
#      - container:osf-sync

  worker:
    volumes_from:
      - container:osf-sync

  admin:
    volumes_from:
      - container:osf-sync

  web:
    volumes_from:
      - container:osf-sync

  api:
    volumes_from:
      - container:osf-sync
